{
 "title": "Kafka Broker",
 "time": { "from": "2026-04-17T10:00:00.000Z", "to": "2026-04-17T10:14:00.000Z" },
 "panels": [
  {
   "title": "Количество Produce-запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_totalproducerequestspersec_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Входящие сообщения в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesinpersec_count{job=\"kafka-jmx\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Максимальное отставание consumer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag_max{client_id=\"consumer-data-consumer-group-1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}