{
 "title": "Kafka Producer Consumer",
 "time": { "from": "2026-04-17T10:00:00.000Z", "to": "2026-04-17T10:14:00.000Z" },
 "panels": [
  {
   "title": "Скорость потребления записей консьюмером",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_manager_records_consumed_rate{client_id=\"consumer-data-consumer-group-1\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Скорость отправки записей продюсером",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_producer_record_send_rate{client_id=\"producer-1\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Частота ошибок при отправке",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_producer_record_error_rate{client_id=\"producer-1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}