{
 "title": "Spring Boot HTTP requests",
 "time": { "from": "2026-04-17T10:00:00.000Z", "to": "2026-04-17T10:14:00.000Z" },
 "panels": [
  {
   "title": "Средняя длительность POST-запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"POST\"}[1m])) / sum(rate(http_server_requests_seconds_count{method=\"POST\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество POST-запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"POST\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Успешные GET-запросы в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{method=\"GET\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95% длительности POST",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"POST\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}